tinkerbell/tinkerbell.org

- README.md
I have updated the readme file with the setup process with and without terraform.
> Update README.md file of tinkerbell.org

- README.md
- setup.html
> fixup (cont.)

- README.md
- setup.html
This PR is to update the tinkerbell.org/setup page to use the method described in https://github.com/tinkerbell/tink/pull/62
- updated sample workflow to be hello world
- updated hardware json block
> update to use single step deployment

- LICENSE
- README.md
> Updated License and Readme

- content/setup/create_servers.md
Updated the terraform section to specify using user api keys
> added notes to terraform section

- content/setup/packet/provisioner.md
> Fixed issue #45 - Corrected the format

- content/examples/hello-world/_index.md
Deployment preview available [here](https://deploy-preview-59--festive-goldwasser-489842.netlify.app/examples/hello-world/).
> Fixed broken link. Now redirects to setup page

- content/examples/hello-world/_index.md
- Added description about few things like `device_1`, it's value MAC address and IP address etc.
- For Preview click [here](https://deploy-preview-63--festive-goldwasser-489842.netlify.app/examples/hello-world/)
> Fix for #120: Update the Hello world example in the website

- content/cli-reference/_index.md
- content/concepts/_index.md
- content/examples/_index.md
- content/examples/hello-world/_index.md
- content/hardware-data/_index.md
- content/setup/packet/hardware-data.md
- content/troubleshooting/_index.md
> Fixed issue #41 - Added sample hardware data in setup guide

- content/examples/_index.md
- added tip under `/examples` for login credentials
- preview [here](https://deploy-preview-70--festive-goldwasser-489842.netlify.app/examples/)
> Documented login credentials for worker 

- layouts/partials/ga.html
- layouts/partials/header.html
- layouts/partials/homepage/header.html
> #51 google analytics code

- content/setup/local-with-vagrant/_index.md
> Updated Vagrant setup documentation 

- content/cli-reference/hardware.md
Updated the example to the new data model
> updated hardware cli reference

- content/architecture/_index.md
Added context with descriptions of the provisioner and the worker.
There is no impact to existing users.
> Update to Architecture doc

- config.toml
- content/documentation/_index.md
Friendly intro docs landing page, basic info and structure.
> Adding Documentation Landing Page

- content/documentation/_index.md
More accurate description text for image repository blurb.
local markdown, preview build
There should be no impact to existing users.
> Updating image repository blurb

- content/cli-reference/workflow.md
Updating the CLI reference to include examples and descriptions and responses for each command.
Final piece of CLI reference update.
A local markdown render and Prettier run.
There should be no impact to existing users.
> Update Workflow CLI reference

- content/setup/local-with-vagrant/_index.md
Adding a little more context around some of the moving parts and hello-world.
Making a hopefully very beginner-level friendly document.
local markdown preview
There should be no impact to existing users.
> rewrite of Vagrant setup

- content/examples/hello-world/_index.md
extension of previous PR - https://github.com/tinkerbell/tinkerbell.org/pull/102. trying to get the checks to run.
local markdown and prettier runs
There shouldn't be any impact to existing users
> refine hello-world example

- content/architecture/_index.md
Adding requirements information for Worker and Provisioner machines.
Requested documentation - https://github.com/tinkerbell/tinkerbell.org/issues/55
local markdown, Prettier run
There should be no impact to existing users.
> Update Architecture with Requirements

- content/architecture/_index.md
- content/examples/hello-world/_index.md
- content/workflows/_index.md
Adding a whole new document to explain workflows - what and how.
Moving content out of the Concepts page into move comprehensive, specialized pages.
Fixes: #
https://github.com/tinkerbell/tinkerbell.org/issues/108
local markdown and prettier
no impact to existing users, but I do have to make sure to reorder, or slide this into the right place in the toc
> Creating a document all about workflows

- content/docs/templates/_index.md
Changes some of the flow and wording of Templates docs.
Hopefully docs read a little bit better and are easier to understand.
I have:
> Templates docs tweaks

- content/docs/setup/terraform/_index.md
Move from tink/deploy to sandbox
https://github.com/tinkerbell/tink/pull/289
https://github.com/tinkerbell/sandbox/pull/13
> Terraform setup guide uses sandbox

- content/docs/setup/local-with-vagrant/_index.md
- content/docs/setup/terraform/_index.md
> Sandbox now uses .env

- config.toml
> add youtube #146

- LICENSE
- README.md
- SUPPORT.md
- config.toml
- content/_index.html
- content/community/contributors/_index.md
- content/community/support.md
- content/docs/_index.md
- content/examples/hello-world/_index.md
- content/homepage/section-1.md
- content/terms/contributor-guide/_index.md
- content/terms/license/_index.md
- layouts/partials/footer.html
- layouts/partials/homepage/footer.html
Signed-off-by: jeremytanner <jeremy@jeremytanner.com>
Rebrands Packet -> Equinix Metal, everywhere except docs & css
Rebranding
> Packet -> Equinix Metal rebrand, everywhere except docs & css

- content/terms/contributor-guide/_index.md
> Updating terms with license info

- content/community/_index.md
- content/faq/_index.md
Issue
- https://github.com/tinkerbell/tinkerbell-docs/issues/37
- https://github.com/tinkerbell/tinkerbell-docs/issues/38
> Fix missing

- static/robots.txt
add robot txt
Issue https://github.com/tinkerbell/tinkerbell.org/issues/183
> Create robots.txt #183

- config.toml
- content/community/_index.md
Issue : https://github.com/tinkerbell/tinkerbell.org/issues/185
> updated community #185

- assets/css/theme-tinkerbell-docs.css
- assets/css/theme-tinkerbell.css
- layouts/partials/footer.html
- layouts/partials/ga.html
- layouts/partials/homepage/footer.html
> Footer update with CNCF #193

- .mergify.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- OWNERS.md
- README.md
- content/terms/contributor-guide/_index.md
Update all refs from master -> main
> Prepare for default branch rename

- content/terms/contributor-guide/_index.md
Updates link to COMMUNICATION.md
As pointed out in https://github.com/tinkerbell/.github/issues/43
> Update COMMUNICATION.md link from .github -> org

- content/_index.html
- content/community/contact.html
- content/examples/netboot-xyz/_index.md
- content/homepage/hero.md
- content/homepage/section-4.md
- layouts/shortcodes/faq.html
- netlify.toml
- src/scss/_settings-docs.scss
- src/scss/_settings.scss
- src/scss/theme-tinkerbell-docs.scss
> Updated dead links, ran prettier.

- content/community/contributors/_index.md
Replaces the outdated contributor avatar view with a link to DevStats which stays accurate over time.
Fixes: #
I have:
> Update the contributor list

- content/terms/contributor-guide/_index.md
The repo has been renamed.
Fixes: #
I have:
> Rename Sandbox to Playground:

- config.toml
- content/_index.html
- content/examples/netboot-xyz/_index.md
- content/homepage/section-1.md
- content/homepage/section-2.md
This PR changes the mentions of Boots on the website to Smee
I came across the website, clicked the link to Boots, and was confused when the repo said Smee
I have:
> Update names from Boots to Smee

- content/docs/concepts/templates.md
- content/docs/concepts/workflows.md
- content/docs/reference/osprimer.md
- data/menu/main.yaml
- layouts/shortcodes/stringparam.html
This completes the documentation for concepts/template
Fixes: #
I have:
> Add templating a template to Template doc

- content/docs/concepts/workflows.md
- content/docs/setup/getting_started.md
- content/docs/setup/install.md
- data/menu/main.yaml
Add production install doc
Fixes: #
I have:
> Add production install doc

- hugo.toml
- layouts/index.html
Add Rufio to homepage
Fixes: #
I have:
> Add Rufio to homepage

- content/docs/integrations/cloudinit.md
Enables users to understand how to get started with cloud-init in Tinkerbell.
Fixes: #
I have:
> Add cloud-init doc:

- content/docs/reference/community.md
- content/homepage/section-1.md
- hugo.toml
> Fix links to community page

- content/docs/setup/install.md
This uses the latest so users have all the latests updates.
Fixes: #
I have:
> Update the Tinkerbell stack Helm chart:

- content/docs/services/tink-worker.md
The HookOS repo change dramatically and the previous links changed. This resolves the links.
Fixes: #238 
I have:
> Fix links to hook-bootkit:

- content/docs/concepts/templates.md
- content/docs/integrations/cloudinit.md
I found mistakes in the Tinkerbell documentation where certain action image links were incorrect. 
Fixes: #
I have:
> Update Action Images in Documentation

- content/docs/concepts/templates.md
The version must be "0.1" as there is code in Tink to check for this exact value.
Fixes: #
I have:
> Fix Template examples:

- content/docs/setup/install.md
Update helm install command too.
Fixes: #
I have:
> Update chart version:

- content/docs/setup/install.md
> Update more references to latest version:

- layouts/landing.html
…thub.com>
Update landing.html for 2025 year
Fixes: #
I have:
> Update all rights for 2025
