tinkerbell/tinkerbell.org

- content/cli-reference/workflow.md
- content/concepts/_index.md
In this commit a "Note" has been in place with template and workflow which defines what you can provide as a key for hardware indexing
> Sanitizing hardwares entry when creating a workflow

- content/hardware-data/_index.md
- content/setup/packet-with-terraform/hardware-data.md
As the hardware data model is being updated by https://github.com/tinkerbell/tink/pull/64, https://github.com/tinkerbell/boots/pull/27, and https://github.com/tinkerbell/hegel/pull/13, the docs should also reflect the changes.
Also sorted the json structures for better predictability
> updated hardware data pages for new data model

- content/setup/local-with-vagrant/_index.md
We introduced a breaking change in the hardware data model which among other things broke the Vagrant setup guide. This fixes it.
> Updated hardware-data.json example in Vagrant setup guide

- content/docs/setup/local-with-vagrant/extending-vagrant.md
The PR adds details about how we can extend the vagrant setup to reuse `osie.tar.gz`.
Preview [here](https://deploy-preview-131--festive-goldwasser-489842.netlify.app/docs/setup/local-with-vagrant/extending-vagrant/#reusing-osietargz).
It helps to reduce the provisioner setup time, resulting in better user experience with the setup. 
I have:
> Extending Vagrant setup to reuse osie.tar.gz

- content/docs/services/hegel.md
it was not clear how to cURL Hegel during the vagrant setup.
I tried to fix that:
https://github.com/tinkerbell/sandbox/issues/12
> Fix hegel HTTP API port

- content/docs/workflows/_index.md
Updates the description of ephemeral data.
Previous description was a little light on the tink-worker view of ephemeral data and how it's read/written.
Note - this PR does not update the diagram, it could use some work, method is tbd.
local markdown, prettier, and will preview build
No impact to users.
> Ephemeral data

- content/docs/setup/terraform/_index.md
I forgot to update from `tink` directory to `sandbox` when it comes to
`cd` inside the cloned repo.
> tink reference left over

- README.md
Our repositories should be the example from which adjacent, competing, projects look for inspiration.
Each repository should not look entirely different from other repositories in the ecosystem, having a different layout, a different testing model, or a different logging model, for example, without reason or recommendation from the subject matter experts from the community.
We should share our improvements with each ecosystem while seeking and respecting the feedback of these communities.
Whether or not strict guidelines have been provided for the project type, our repositories should ensure that the same components are offered across the board. How these components are provided may vary, based on the conventions of the project type. GitHub provides general guidance on this which they …
> Change maintenance status in README to experimental.

- config.toml
- layouts/partials/homepage/footer.html
- Update link menu docs to https://docs.tinkerbell.org/
- change footer icon + title to icon
> update link docs and footer icon #149

- content/community/slack.html
Change Packet to Equinix Metal in copy and link
Changes copy and link from Packet to Equinix Metal on the Tinkerbell Community Slack page
Rebrand
> Packet -> Equinix Metal Slack

- content/faq/_index.md
FAQ Page update Packet -> Equinix Metal
Changes Packet to Equinix Metal on the FAQ page
Rebrand
> Packet to Equinix Metal FAQ

- content/terms/contributor-guide/_index.md
Split non-DCO bullets out of the DCO block quote.
This makes it look like the bullet points are part of the DCO, when it is not the case.
> Split non-DCO bullets from DCO block quote

- netlify.toml
Add redirection from /docs to https://docs.tinkerbell.org/
Issue https://github.com/tinkerbell/tinkerbell.org/issues/160
Open url /docs then redirect to https://docs.tinkerbell.org/
> redirection /docs to https://docs.tinkerbell.org/ #160

- layouts/partials/menu.html
Corrects `gotpl` syntax to use `or` as a function.
In the 0.71.1 release of `hugo` there was a change that broke older compatibilities with `gotpl`. 
Fixes: #133 
I ran the site in a container locally
```bash
docker run --rm -it -v $(pwd):/src \
-p 1313:1313 klakegg/hugo:0.82.0-alpine server
```
Then I manually tested functionality of the site; link, copy text boxes, top nav, side bars, etc.
Fixes a bug that prevented upgrading the site release to `hugo` `v0.82.0` or _latest_. 
I have:
> bug: fix gotpl with or function

- content/community/_index.md
- content/community/contact.html
- content/community/contributors/_index.md
Move Slack link to CNCF, update mailing-list information
The Slack channel has moved, and the current e-mail address listed does not facilitate discussions.
`hugo server -D`
The current Slack channel and e-mail address are not helpful to people curious about what is going on with Tinkerbell.
> Move Slack link to CNCF, update mailing-list information

- content/community/_index.md
Include Community calls in the "Join Us" section of community. Given greater weight than the Twitter (now X) and Youtube channels which haven't been actively engaged.
Fixes: #
I have:
> Add Community meetings to Community page

- hugo.toml
- layouts/partials/page-header.html
- static/custom.css
They were going to the homepage with `geekdocOverwriteHTMLBase = true`.
Add page edit links to make it easier for folks to contribute.
Fixes: #199 
I have:
> Fix anchor links add page edit links:

- content/docs/concepts/templates.md
Update example templates so they work out of the box when copy-pasting.
- Add the required name and version to spec.data
- Fix URL to action images
Currently the template examples does not work out of the box and for a newcomer it is not evident why they fail, or how to troubleshoot.
This is needed to give a good first impression for newcomers.
I have:
> Fix template examples

- content/docs/setup/getting_started.md
Fix paths to vagrant configs in both playground and sandbox repos
To fix minor bugs while following https://tinkerbell.org/docs/setup/getting_started
Fixes: #
I have:
> Fix paths to vagrant configs in both playground and sandbox repos

- content/docs/additionalcomponents/ipxe.md
- content/docs/concepts/hardware.md
- content/docs/concepts/templates.md
- content/docs/concepts/workflows.md
- content/docs/services/rufio.md
- content/docs/services/smee.md
- content/docs/services/tink-server.md
- content/docs/services/tootles.md
- content/docs/setup/install.md
- hugo.toml
- layouts/shortcodes/repo_tree.html
- layouts/shortcodes/tinkerbell_version.html
This PR is another grapbag of updates to the documentation.
There are now `params.tinkerbellVersion` and `params.tinkerbellRepo` settings in the `hugo.toml` file. These are then used in two new shortcodes.
The first one is `tinkerbell_version`. It doesn't take any parameters and just outputs the value of `params.tinkerbellVersion`.
The second is `repo_tree`. It takes the `tinkerbellRepo` and `tinkerbellVersion` plus an argument and constructs a path from those.
For example, `{{ repo_tree "README.md" }}` would result in this address: https://github.com/tinkerbell/tinkerbell/tree/v0.18.3/README.md
The idea behind these is that we don't have to touch a dozen links when we do an update.
In contrast to what the docs said, more than just the `Hardware.Disks` values could be used from the …
> Another set of documentation updates

- content/docs/setup/getting_started.md
I played through the Getting Started page and found two small improvements:
- The page still mentions a Kubernetes Job for downloading HookOS, but that's now done in an init container, so I removed the mention
- I also added another step for cleaning up the VMs once the reader is done with the playground, running `vagrant destroy`
No issue was raised, just a couple of small things I found.
I played through the playground instructions on a Fedora machine, and everything worked as expected.
No impact for existing users.
I have:
> Some small updates to the Getting Started page

- hugo.toml
Updating the docs to the newest Tinkerbell version.
Updated the Tinkerbell version for the docs page to `0.19.1`, so it points to the newest Tinkerbell release.
Tinkerbell 0.19.1 was released yesterday.
Ran Hugo locally and checked a couple of the links which use the version as part of the URL.
No impact for existing users.
I have:
> Update Tinkerbell version to 0.19.1

- content/docs/services/tink-controller.md
- content/docs/services/tink-server.md
- content/docs/services/tink-worker.md
This small set of changes fixes a few small issues on the Tink Server, Controller and Worker pages and removes all of the empty sections.
General documentation cleanup.
I ran a local Hugo server and checked the changed pages.
No impact for existing users.
I have:
> Some doc improvements for the Tink Server/Controller/Worker pages

- content/docs/concepts/hardware.md
- content/docs/concepts/templates.md
- content/docs/integrations/cloudinit.md
- content/docs/setup/getting_started.md
As `tinkerbell` is now the namespace used in the Install page examples, this PR replaces all occurrences of the old `tink-system` namespace.
Just making sure all of the documentation uses a consistent namespace.
No testing has been conducted.
No impact on existing users.
I have:
> Replace tink-system namespace with tinkerbell
